[package]
name = "merkle-mountain-range"
version = "0.1.0"
authors = ["Andreas Doerr"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { version = "2.1.1", package = "parity-scale-codec", default-features = false, features = ["derive"] }

blake2 = "0.9.*"
thiserror = "1.0.*"

[features]
default = ["std"]
std = [
	"codec/std",
]