[package]
name = "arber"
authors = ["Andreas Doerr"]
version = "0.0.1"
edition = "2018"

description = "A Merkle-Mountain-Range (MMR) library"
repository = "http://github.com/adoerr/arber"
readme = "README.md"
keywords = ["mmr", "merkle-trees", "crypto", "accumulator"]
categories = ["data-structures"]
license = "Apache-2.0"

[dependencies]
codec = { version = "2.1.1", package = "parity-scale-codec", default-features = false, features = ["derive"] }

blake2 = "0.9.*"
thiserror = "1.0.*"

[features]
default = ["std"]
std = [
	"codec/std",
]